const NAME_DESCRIPTIONS_RICH = {

  "Adam": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Adam pochodzi z języka <strong>hebrajskiego</strong>. Wywodzi się najprawdopodobniej od słowa <em>adamah</em>, oznaczającego „ziemię, rolę" — stąd znaczenie „zrodzony z ziemi" lub „rolnik". Możliwe też pochodzenie od słowa <em>adom</em> („czerwony", od koloru gliny). W językach ałtajskich <em>adam</em> oznacza „człowiek".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Adam to jedno z najstarszych imion chrześcijańskich — znane z Biblii jako imię pierwszego człowieka. W Polsce używane od wieków. Dziś należy do najczęstszych polskich imion męskich (miejsce 20. wg PESEL).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Adaś, Adi, Adek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Adam (ang., niem., franc., hiszp.), Ádám (węg.), Adão (port.), Ādam (arab.), Адам (ros., ukr.)</p></div>',

  "Anna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Anna pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>hannāh</em> oznaczającego „łaska" lub „pełna łaski". Jest to jedno z najstarszych i najszerzej rozpowszechnionych imion na świecie.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię Anna pojawia się już od <strong>1229 roku</strong>. Przez wieki należało do czołowych imion żeńskich — dziś nosi je ponad milion Polek, co czyni je <strong>najczęstszym imieniem żeńskim w Polsce</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ania, Anka, Anusia, Hania, Hanka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Ann, Anne (ang.), Anne (franc.), Ana (hiszp.), Аnna (ros.), Hanna (niem., skandynaw.)</p></div>',

  "Piotr": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Piotr pochodzi z języka <strong>greckiego</strong> — od słowa <em>petros</em> oznaczającego „skała" lub „kamień". Jest formą aramejskiego imienia Kefas, nadanego Szymonowi przez Jezusa.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozpowszechniło się w Europie dzięki kultowi świętego Piotra Apostoła — pierwszego papieża. W Polsce jest jednym z najstarszych i najpopularniejszych imion męskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Piotrek, Piotruś, Piotreczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Peter (ang., niem.), Pierre (franc.), Pedro (hiszp.), Pietro (wł.), Pyotr (ros.), Péter (węg.)</p></div>',

  "Krzysztof": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Krzysztof pochodzi z języka <strong>greckiego</strong> — od słów <em>Christos</em> (Chrystus) i <em>phero</em> (nieść), co oznacza dosłownie <strong>„niosący Chrystusa"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię pojawiło się w <strong>XIV wieku</strong>, początkowo wśród szlachty, wraz z przyjęciem chrześcijaństwa. Dziś jest drugim najpopularniejszym imieniem męskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Krzysiek, Krzyś, Kris</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Christopher (ang.), Christoph (niem.), Christophe (franc.), Cristóbal (hiszp.), Cristoforo (wł.), Христофор (ros.)</p></div>',

  "Katarzyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Katarzyna pochodzi z języka <strong>greckiego</strong> — od słowa <em>katharos</em> oznaczającego „czysta", „nieskalana". Do Polski dotarło przez łacinę.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane jest od <strong>XII wieku</strong>. Od XV wieku przez wiele stuleci należało do trzech najpopularniejszych imion żeńskich. Dziś jest drugim najpopularniejszym imieniem żeńskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Kasia, Kaśka, Katiusza, Kachna</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Catherine, Katherine (ang.), Katharina (niem.), Catherine (franc.), Catalina (hiszp.), Ekaterina (ros.)</p></div>',

  "Małgorzata": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Małgorzata pochodzi z łaciny — od słowa <em>margarita</em>, które z kolei wywodzi się z języka <strong>greckiego</strong> <em>margarites</em> oznaczającego <strong>„perła"</strong>. Polska forma powstała przez uproszczenie (r-r → ł-r).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Historyczne zapisy z Polski: <em>Margorzata</em> (1438), <em>Malgorzatha</em> (1468). Przez wieki jedno z czołowych imion żeńskich — dziś czwarte najpopularniejsze w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Małgosia, Gosia, Gośka, Ryta, Greta</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Margaret (ang.), Margarete (niem.), Marguerite (franc.), Margarita (hiszp.), Margherita (wł.), Маргарита (ros.)</p></div>',

  "Agnieszka": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Agnieszka pochodzi z języka <strong>greckiego</strong> — od słowa <em>hagnē</em> oznaczającego „czysta", „dziewicza", „nieskalana". Możliwe też nawiązanie do łacińskiego <em>agnus</em> — „baranek". Do Polski dotarło wraz z chrześcijaństwem.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, zaadaptowane z łacińskiej formy <em>Agnes</em>. Patronką jest święta Agnieszka Rzymska (†304), męczennica wczesnego chrześcijaństwa.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Aga, Agniecha, Jagna, Inka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Agnes (ang., niem.), Agnès (franc.), Inés (hiszp.), Ágnes (węg.), Агнесса (ros.)</p></div>',

  "Tomasz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Tomasz pochodzi z języka <strong>aramejskiego</strong> — od słowa <em>toma</em> oznaczającego <strong>„bliźniak"</strong>. Nosił je jeden z dwunastu apostołów Jezusa, znany jako „Tomasz Niedowiarek".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię trafiło do Polski wraz z chrześcijaństwem i przez wieki należało do najpopularniejszych. Dziś jest trzecim najpopularniejszym imieniem męskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Tomek, Tomuś, Tomcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Thomas (ang., niem.), Tomás (hiszp.), Tommaso (wł.), Tamás (węg.), Фома (ros.)</p></div>',

  "Paweł": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Paweł pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>paulus</em> oznaczającego <strong>„mały"</strong>, „skromny". Było to popularne imię w starożytnym Rzymie, znane szczególnie dzięki świętemu Pawłowi Apostołowi.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię Paweł dokumentowane jest od <strong>XII wieku</strong> (łac. <em>Paulus</em>, 1155). Dało początek licznym polskim nazwom miejscowym i nazwiskom: Pawlak, Paszek, Pawłów.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Pawełek, Pawcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Paul (ang., niem., franc.), Pablo (hiszp.), Paolo (wł.), Pál (węg.), Павел (ros.)</p></div>',

};
