const NAME_DESCRIPTIONS_RICH = {

  "Adam": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Adam pochodzi z języka <strong>hebrajskiego</strong>. Wywodzi się najprawdopodobniej od słowa <em>adamah</em>, oznaczającego „ziemię, rolę" — stąd znaczenie „zrodzony z ziemi" lub „rolnik". Możliwe też pochodzenie od słowa <em>adom</em> („czerwony", od koloru gliny). W językach ałtajskich <em>adam</em> oznacza „człowiek".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Adam to jedno z najstarszych imion chrześcijańskich — znane z Biblii jako imię pierwszego człowieka. W Polsce używane od wieków. Dziś należy do najczęstszych polskich imion męskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Adaś, Adi, Adek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Adam (ang., niem., franc., hiszp.), Ádám (węg.), Adão (port.), Ādam (arab.), Адам (ros., ukr.)</p></div>',

  "Anna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Anna pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>hannāh</em> oznaczającego „łaska" lub „pełna łaski". Jest to jedno z najstarszych i najszerzej rozpowszechnionych imion na świecie.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię Anna pojawia się już od <strong>1229 roku</strong>. Przez wieki należało do czołowych imion żeńskich — dziś nosi je ponad milion Polek, co czyni je <strong>najczęstszym imieniem żeńskim w Polsce</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ania, Anka, Anusia, Hania, Hanka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Ann, Anne (ang.), Anne (franc.), Ana (hiszp.), Anna (ros.), Hanna (niem., skandynaw.)</p></div>',

  "Piotr": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Piotr pochodzi z języka <strong>greckiego</strong> — od słowa <em>petros</em> oznaczającego „skała" lub „kamień". Jest formą aramejskiego imienia Kefas, nadanego Szymonowi przez Jezusa.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozpowszechniło się w Europie dzięki kultowi świętego Piotra Apostoła — pierwszego papieża. W Polsce jest jednym z najstarszych i najpopularniejszych imion męskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Piotrek, Piotruś, Piotreczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Peter (ang., niem.), Pierre (franc.), Pedro (hiszp.), Pietro (wł.), Pyotr (ros.), Péter (węg.)</p></div>',

  "Krzysztof": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Krzysztof pochodzi z języka <strong>greckiego</strong> — od słów <em>Christos</em> (Chrystus) i <em>phero</em> (nieść), co oznacza dosłownie <strong>„niosący Chrystusa"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię pojawiło się w <strong>XIV wieku</strong>, początkowo wśród szlachty, wraz z przyjęciem chrześcijaństwa. Dziś jest jednym z najpopularniejszych imion męskich w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Krzysiek, Krzyś, Kris</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Christopher (ang.), Christoph (niem.), Christophe (franc.), Cristóbal (hiszp.), Cristoforo (wł.), Христофор (ros.)</p></div>',

  "Katarzyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Katarzyna pochodzi z języka <strong>greckiego</strong> — od słowa <em>katharos</em> oznaczającego „czysta", „nieskalana". Do Polski dotarło przez łacinę.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane jest od <strong>XII wieku</strong>. Od XV wieku przez wiele stuleci należało do trzech najpopularniejszych imion żeńskich. Dziś jest drugim najpopularniejszym imieniem żeńskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Kasia, Kaśka, Katiusza, Kachna</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Catherine, Katherine (ang.), Katharina (niem.), Catherine (franc.), Catalina (hiszp.), Ekaterina (ros.)</p></div>',

  "Małgorzata": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Małgorzata pochodzi z łaciny — od słowa <em>margarita</em>, które z kolei wywodzi się z języka <strong>greckiego</strong> <em>margarites</em> oznaczającego <strong>„perła"</strong>. Polska forma powstała przez uproszczenie (r-r → ł-r).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Historyczne zapisy z Polski: <em>Margorzata</em> (1438), <em>Malgorzatha</em> (1468). Przez wieki jedno z czołowych imion żeńskich — dziś czwarte najpopularniejsze w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Małgosia, Gosia, Gośka, Greta</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Margaret (ang.), Margarete (niem.), Marguerite (franc.), Margarita (hiszp.), Margherita (wł.), Маргарита (ros.)</p></div>',

  "Agnieszka": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Agnieszka pochodzi z języka <strong>greckiego</strong> — od słowa <em>hagnē</em> oznaczającego „czysta", „dziewicza", „nieskalana". Możliwe też nawiązanie do łacińskiego <em>agnus</em> — „baranek". Do Polski dotarło wraz z chrześcijaństwem.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, zaadaptowane z łacińskiej formy <em>Agnes</em>. Patronką jest święta Agnieszka Rzymska (†304), męczennica wczesnego chrześcijaństwa.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Aga, Agniecha, Jagna, Inka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Agnes (ang., niem.), Agnès (franc.), Inés (hiszp.), Ágnes (węg.), Агнесса (ros.)</p></div>',

  "Tomasz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Tomasz pochodzi z języka <strong>aramejskiego</strong> — od słowa <em>toma</em> oznaczającego <strong>„bliźniak"</strong>. Nosił je jeden z dwunastu apostołów Jezusa, znany jako „Tomasz Niedowiarek".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię trafiło do Polski wraz z chrześcijaństwem i przez wieki należało do najpopularniejszych. Dziś jest trzecim najpopularniejszym imieniem męskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Tomek, Tomuś, Tomcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Thomas (ang., niem.), Tomás (hiszp.), Tommaso (wł.), Tamás (węg.), Фома (ros.)</p></div>',

  "Andrzej": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Andrzej pochodzi z języka <strong>greckiego</strong> — od rdzenia <em>andr-</em> oznaczającego „mężczyzna", „mężny", „odważny". Jest polską formą greckiego imienia Andreas.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków dzięki kultowi świętego Andrzeja Apostoła — brata Szymona Piotra. Historyczna forma <em>Jędrzej</em> była powszechna w XVII-XVIII wieku. Z imieniem związane są tradycyjne <strong>andrzejki</strong> — wróżby z 29 na 30 listopada.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Jędrek, Jędruś, Andrzejek, Andy</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Andrew (ang.), Andreas (niem.), André (franc.), Andrés (hiszp.), Andrea (wł.), Андрей (ros.)</p></div>',

  "Paweł": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Paweł pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>paulus</em> oznaczającego <strong>„mały"</strong>, „skromny". Było to popularne imię w starożytnym Rzymie, znane szczególnie dzięki świętemu Pawłowi Apostołowi.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię Paweł dokumentowane jest od <strong>XII wieku</strong> (łac. <em>Paulus</em>, 1155). Dało początek licznym polskim nazwom miejscowym i nazwiskom: Pawlak, Paszek, Pawłów.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Pawełek, Pawcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Paul (ang., niem., franc.), Pablo (hiszp.), Paolo (wł.), Pál (węg.), Павел (ros.)</p></div>',

  "Michał": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Michał pochodzi z języka <strong>hebrajskiego</strong> — od pytania retorycznego <em>Mikha-El</em> oznaczającego <strong>„któż jest jak Bóg?"</strong>. Nosił je archanioł Michał — obrońca i wojownik niebieski.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozpowszechniło się w Polsce wraz z chrześcijaństwem. Dziś jest jednym z najpopularniejszych imion męskich — nosi je blisko pół miliona Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Michałek, Michaś, Misiek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Michael (ang., niem.), Michel (franc.), Miguel (hiszp.), Michele (wł.), Mikhail (ros.), Mihail (rum.)</p></div>',

  "Ewa": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Ewa pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>hawwah</em> oznaczającego <strong>„życie"</strong> lub „dawczyni życia". Według Biblii Ewa była pierwszą kobietą — matką całej ludzkości.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno z najstarszych imion chrześcijańskich, znane z Księgi Rodzaju. W Polsce przez wieki należało do czołowych imion żeńskich — dziś nosi je blisko pół miliona Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ewka, Ewcia, Ewusia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Eve (ang.), Eva (niem., hiszp., wł.), Ève (franc.), Eva (ros.), Éva (węg.)</p></div>',

  "Barbara": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Barbara pochodzi z języka <strong>greckiego</strong> — od słowa <em>barbaros</em> oznaczającego „obcy", „cudzoziemiec". W starożytności Grecy tak nazywali wszystkich nie mówiących po grecku.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię znane od wieków. Patronką jest <strong>święta Barbara z Nikomedii</strong> — legendarna męczennica z III/IV wieku, której wspomnienie obchodzone jest 4 grudnia. Z jej imieniem związane są liczne polskie przysłowia pogodowe.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Basia, Baśka, Basieńka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Barbara (ang., niem., franc., hiszp.), Barbora (czes., słowac.), Warwara (ros., ukr.)</p></div>',

  "Jan": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jan pochodzi z języka <strong>hebrajskiego</strong> — od imienia <em>Johanan</em> oznaczającego <strong>„Bóg jest łaskawy"</strong>. Do Polski dotarło przez grekę i łacinę.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno z najstarszych i najpopularniejszych imion w Polsce — dokumentowane od <strong>1012 roku</strong> (jako <em>Ioannes</em>), od <strong>1161 roku</strong> w formie Jan. Przez wieki należało do najczęstszych imion męskich w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Janek, Jasiek, Jaś, Jaszko</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>John, Ian (ang.), Jean (franc.), Juan (hiszp.), Johannes (niem.), Giovanni (wł.), Иван (ros.)</p></div>',

  "Marcin": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Marcin pochodzi z języka <strong>łacińskiego</strong> — od imienia <em>Martinus</em>, które wywodzi się od imienia boga wojny <strong>Marsa</strong>. Oznacza dosłownie „należący do Marsa".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię poświadczone od <strong>1393 roku</strong> w księgach krakowskich. Popularność zawdzięcza kultowi świętego Marcina z Tours — jego święto (11 listopada) jest w Polsce tradycyjnie obchodzone rogalami świętomarcińskimi.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Marcinek, Martuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Martin (ang., niem., franc., hiszp.), Martino (wł.), Márton (węg.), Мартин (ros.)</p></div>',

  "Magdalena": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Magdalena pochodzi od nazwy miejscowości <strong>Magdala</strong> nad Jeziorem Galilejskim. Dosłownie oznacza „kobieta z Magdali". Imię ściśle związane z postacią <strong>Marii Magdaleny</strong> z Nowego Testamentu.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię trafiło do Polski wraz z chrześcijaństwem. Dziś nosi je ponad 430 tysięcy Polek — jest ósmym najpopularniejszym imieniem żeńskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Magda, Madzia, Lena</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Madeleine (franc.), Madeline (ang.), Magdalena (niem., hiszp.), Maddalena (wł.), Magdaléna (czes.)</p></div>',

  "Jakub": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jakub pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>Yaakov</em> (יַעֲקֹב), co oznacza „trzymający za piętę" lub „ten, który zastępuje". W Biblii Jakub był synem Izaaka i wnukiem Abrahama — praojciec dwunastu plemion Izraela.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozpowszechniło się w Polsce dzięki dwóm apostołom noszącym to imię: Jakubowi Starszemu i Jakubowi Młodszemu. Dziś jest jednym z najpopularniejszych imion dla chłopców.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Kuba, Kubek, Kubuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>James, Jacob (ang.), Jacques (franc.), Jaime (hiszp.), Giacomo (wł.), Jakob (niem.), Яков (ros.)</p></div>',

  "Elżbieta": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Elżbieta pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>Eliszeba</em> (אלשבת) oznaczającego <strong>„Bóg moją przysięgą"</strong> lub „mój Bóg jest pełnią". W Biblii nosiła je matka Jana Chrzciciela.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków. Noszone przez liczne królowe i cesarzowe — m.in. Elżbietę I i II królową Anglii. Dziś jest dziewiątym najpopularniejszym imieniem żeńskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ela, Elka, Elcia, Elunia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Elizabeth (ang.), Elisabeth (niem., franc.), Isabel (hiszp.), Elisabetta (wł.), Erzsébet (węg.), Елизавета (ros.)</p></div>',

  "Joanna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Joanna pochodzi z języka <strong>hebrajskiego</strong> — od imienia <em>Jo-hanan</em> oznaczającego <strong>„Bóg jest łaskawy"</strong>. Jest żeńską formą imienia Jan.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię obecne od <strong>XIII wieku</strong>, dokumentowane m.in. w formie Johanna i Jana. Forma Joanna pojawia się od <strong>1399 roku</strong>. Dziś nosi je ponad 400 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Joasia, Asia, Aśka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Joan, Joanne (ang.), Jeanne (franc.), Juana (hiszp.), Johanna (niem.), Giovanna (wł.)</p></div>',

  "Aleksandra": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Aleksandra pochodzi z języka <strong>greckiego</strong> — od słów <em>alexein</em> (bronić, chronić) i <em>anēr</em> (mężczyzna), co oznacza <strong>„obrończyni ludzi"</strong>. Jest żeńską formą imienia Aleksander.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię weszło w użycie w <strong>XIV wieku</strong>. Popularność zyskało m.in. dzięki powieści Henryka Sienkiewicza <em>Potop</em>, gdzie jedna z bohaterek nosiła to imię.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ola, Oleńka, Sandra, Alesia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Alexandra (ang., niem.), Alexandrine (franc.), Alejandra (hiszp.), Alessandra (wł.), Александра (ros.)</p></div>',

  "Krystyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Krystyna pochodzi z języka <strong>greckiego</strong> — od słowa <em>Christianos</em> oznaczającego <strong>„chrześcijanka"</strong>, czyli „należąca do Chrystusa". Jest żeńską formą imienia Krystian.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, noszone przez liczne święte i królowe europejskie. Szczyt popularności przypadał na lata 50.-70. XX wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Krysia, Krysieńka, Kryska</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Christina, Christine (ang., niem.), Christine (franc.), Cristina (hiszp., wł.), Кристина (ros.)</p></div>',

  "Łukasz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Łukasz pochodzi z języka <strong>greckiego</strong> — od słowa <em>Loukas</em>, nawiązującego do łacińskiego <em>lux</em> (światło) lub nazwy krainy Lukania we Włoszech. Oznacza „urodzony o świcie" lub „niosący światło".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce dzięki świętemu Łukaszowi Ewangeliście — autorowi trzeciej Ewangelii i Dziejów Apostolskich. Dziś nosi je blisko 380 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Łukaszek, Łukasz</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Lucas, Luke (ang.), Lukas (niem.), Luc (franc.), Lucas (hiszp.), Luca (wł.), Lukáš (czes.)</p></div>',

  "Mateusz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Mateusz pochodzi z języka <strong>hebrajskiego</strong> — od słów <em>mattan</em> (dar) i <em>Yah</em> (Jahwe), co oznacza <strong>„dar Boga"</strong>. Nosił je Mateusz Apostoł i Ewangelista.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W dawnej Polsce imiona Mateusz i Maciej nie były rozróżniane aż do <strong>XVI wieku</strong>. W źródłach pojawia się jako <em>Mathaeus</em> i <em>Matyjasz</em>. Dziś nosi je ponad 370 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Mateuszek, Matek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Matthew (ang.), Matthias (niem.), Mathieu (franc.), Mateo (hiszp.), Matteo (wł.), Матвей (ros.)</p></div>',

  "Monika": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Etymologia imienia Monika jest niepewna. Prawdopodobnie pochodzi z języka <strong>greckiego</strong> — od słowa <em>monos</em> (jeden, jedyny) lub <em>monaché</em> (samotna, odosobniona). Możliwe też pochodzenie afrykańskie.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię pojawia się już w <strong>XV wieku</strong> w formach Mońka i Muńka. Szerszą popularność zyskało w XIX wieku, a szczyt przypadał na lata 70. XX wieku. Patronką jest święta Monika — matka świętego Augustyna.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Moniczka, Monia, Nika</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Monica (ang., wł., hiszp.), Monique (franc.), Mónika (węg.), Моника (ros.)</p></div>',

  "Grzegorz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Grzegorz pochodzi z języka <strong>greckiego</strong> — od słowa <em>gregoreo</em> oznaczającego <strong>„być czujnym"</strong>, „czuwać". Jest polską formą łacińskiego <em>Gregorius</em>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię bardzo popularne w historii chrześcijaństwa — nosił je aż <strong>16 papieży</strong>, w tym Grzegorz I Wielki (papież, doktor Kościoła). W Polsce używane od wieków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Grześ, Grześko, Grzesiek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Gregory (ang.), Gregor (niem.), Grégoire (franc.), Gregorio (hiszp., wł.), Grigorij (ros.)</p></div>',

  "Marek": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Marek pochodzi z języka <strong>łacińskiego</strong> — wywodzi się od imienia boga wojny <strong>Marsa</strong> (<em>Mart-ico-s</em>), oznaczając „należący do Marsa". Należy do grupy starożytnych imion rzymskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce dokumentowane od <strong>XIII wieku</strong> w formach Marek, Marko, Markusz. Patronem jest <strong>święty Marek Ewangelista</strong> — autor drugiej Ewangelii, którego święto przypada 25 kwietnia.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Maruś, Mareczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Mark (ang.), Markus (niem.), Marc (franc.), Marcos (hiszp.), Marco (wł.), Марк (ros.)</p></div>',

  "Zofia": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Zofia pochodzi z języka <strong>greckiego</strong> — od słowa <em>sophía</em> (σοφία) oznaczającego <strong>„mądrość"</strong>. Jest jednym z najpiękniejszych semantycznie imion żeńskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, noszone przez liczne polskie księżniczki i królowe. W <strong>2022 roku</strong> było najczęściej nadawanym imieniem dla dziewczynek w Polsce. Dziś nosi je blisko 365 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Zosia, Zośka, Sonia, Sosia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Sophie, Sophia (ang., franc.), Sofia (hiszp., wł.), Sofie (niem.), София (ros.)</p></div>',

  "Stanisław": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Stanisław jest imię <strong>słowiańskie</strong> — złożone z członów <em>stani-</em> (stanąć, powstać) i <em>-sław</em> (sława), co oznacza <strong>„ten, który stanie się sławny"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno z najbardziej polskich imion — pod koniec XV wieku należało do najpopularniejszych w kraju. Patronem jest <strong>święty Stanisław ze Szczepanowa</strong> — biskup krakowski, patron Polski, męczennik (†1079).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Staś, Stasio, Stasiek, Staszek, Stach</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Stanislaus (łac., niem.), Stanislas (franc.), Estanislao (hiszp.), Szaniszló (węg.), Станислав (ros.)</p></div>',

  "Wojciech": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Wojciech jest imieniem <strong>słowiańskim</strong> — złożonym z członów <em>woj-</em> (wojownik, żołnierz) i <em>-ciech</em> (radość, pociecha), co oznacza <strong>„wojownik przynoszący radość"</strong> lub „pociecha wojska".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od <strong>X wieku</strong>. Patronem jest <strong>święty Wojciech</strong> — czeski biskup, misjonarz i męczennik (†997), patron Polski. Jego imieniny obchodzone są 23 kwietnia.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Wojtek, Wojtuś, Wojtas, Wojcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Adalbert (łac., niem.), Vojtěch (czes.) — imię w swej polskiej formie nie ma bezpośrednich odpowiedników w językach zachodnich.</p></div>',

};
