const NAME_DESCRIPTIONS_RICH = {

  "Adam": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Adam pochodzi z języka <strong>hebrajskiego</strong>. Wywodzi się najprawdopodobniej od słowa <em>adamah</em>, oznaczającego „ziemię, rolę" — stąd znaczenie „zrodzony z ziemi" lub „rolnik". Możliwe też pochodzenie od słowa <em>adom</em> („czerwony", od koloru gliny). W językach ałtajskich <em>adam</em> oznacza „człowiek".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Adam to jedno z najstarszych imion chrześcijańskich — znane z Biblii jako imię pierwszego człowieka. W Polsce używane od wieków. Dziś należy do najczęstszych polskich imion męskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Adaś, Adi, Adek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Adam (ang., niem., franc., hiszp.), Ádám (węg.), Adão (port.), Ādam (arab.), Адам (ros., ukr.)</p></div>',

  "Anna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Anna pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>hannāh</em> oznaczającego „łaska" lub „pełna łaski". Jest to jedno z najstarszych i najszerzej rozpowszechnionych imion na świecie.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię Anna pojawia się już od <strong>1229 roku</strong>. Przez wieki należało do czołowych imion żeńskich — dziś nosi je ponad milion Polek, co czyni je <strong>najczęstszym imieniem żeńskim w Polsce</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ania, Anka, Anusia, Hania, Hanka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Ann, Anne (ang.), Anne (franc.), Ana (hiszp.), Anna (ros.), Hanna (niem., skandynaw.)</p></div>',

  "Piotr": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Piotr pochodzi z języka <strong>greckiego</strong> — od słowa <em>petros</em> oznaczającego „skała" lub „kamień". Jest formą aramejskiego imienia Kefas, nadanego Szymonowi przez Jezusa.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozpowszechniło się w Europie dzięki kultowi świętego Piotra Apostoła — pierwszego papieża. W Polsce jest jednym z najstarszych i najpopularniejszych imion męskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Piotrek, Piotruś, Piotreczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Peter (ang., niem.), Pierre (franc.), Pedro (hiszp.), Pietro (wł.), Pyotr (ros.), Péter (węg.)</p></div>',

  "Krzysztof": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Krzysztof pochodzi z języka <strong>greckiego</strong> — od słów <em>Christos</em> (Chrystus) i <em>phero</em> (nieść), co oznacza dosłownie <strong>„niosący Chrystusa"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię pojawiło się w <strong>XIV wieku</strong>, początkowo wśród szlachty, wraz z przyjęciem chrześcijaństwa. Dziś jest jednym z najpopularniejszych imion męskich w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Krzysiek, Krzyś, Kris</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Christopher (ang.), Christoph (niem.), Christophe (franc.), Cristóbal (hiszp.), Cristoforo (wł.), Христофор (ros.)</p></div>',

  "Katarzyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Katarzyna pochodzi z języka <strong>greckiego</strong> — od słowa <em>katharos</em> oznaczającego „czysta", „nieskalana". Do Polski dotarło przez łacinę.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane jest od <strong>XII wieku</strong>. Od XV wieku przez wiele stuleci należało do trzech najpopularniejszych imion żeńskich. Dziś jest drugim najpopularniejszym imieniem żeńskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Kasia, Kaśka, Katiusza, Kachna</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Catherine, Katherine (ang.), Katharina (niem.), Catherine (franc.), Catalina (hiszp.), Ekaterina (ros.)</p></div>',

  "Małgorzata": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Małgorzata pochodzi z łaciny — od słowa <em>margarita</em>, które z kolei wywodzi się z języka <strong>greckiego</strong> <em>margarites</em> oznaczającego <strong>„perła"</strong>. Polska forma powstała przez uproszczenie (r-r → ł-r).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Historyczne zapisy z Polski: <em>Margorzata</em> (1438), <em>Malgorzatha</em> (1468). Przez wieki jedno z czołowych imion żeńskich — dziś czwarte najpopularniejsze w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Małgosia, Gosia, Gośka, Greta</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Margaret (ang.), Margarete (niem.), Marguerite (franc.), Margarita (hiszp.), Margherita (wł.), Маргарита (ros.)</p></div>',

  "Agnieszka": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Agnieszka pochodzi z języka <strong>greckiego</strong> — od słowa <em>hagnē</em> oznaczającego „czysta", „dziewicza", „nieskalana". Możliwe też nawiązanie do łacińskiego <em>agnus</em> — „baranek". Do Polski dotarło wraz z chrześcijaństwem.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, zaadaptowane z łacińskiej formy <em>Agnes</em>. Patronką jest święta Agnieszka Rzymska (†304), męczennica wczesnego chrześcijaństwa.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Aga, Agniecha, Jagna, Inka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Agnes (ang., niem.), Agnès (franc.), Inés (hiszp.), Ágnes (węg.), Агнесса (ros.)</p></div>',

  "Tomasz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Tomasz pochodzi z języka <strong>aramejskiego</strong> — od słowa <em>toma</em> oznaczającego <strong>„bliźniak"</strong>. Nosił je jeden z dwunastu apostołów Jezusa, znany jako „Tomasz Niedowiarek".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię trafiło do Polski wraz z chrześcijaństwem i przez wieki należało do najpopularniejszych. Dziś jest trzecim najpopularniejszym imieniem męskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Tomek, Tomuś, Tomcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Thomas (ang., niem.), Tomás (hiszp.), Tommaso (wł.), Tamás (węg.), Фома (ros.)</p></div>',

  "Andrzej": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Andrzej pochodzi z języka <strong>greckiego</strong> — od rdzenia <em>andr-</em> oznaczającego „mężczyzna", „mężny", „odważny". Jest polską formą greckiego imienia Andreas.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków dzięki kultowi świętego Andrzeja Apostoła — brata Szymona Piotra. Historyczna forma <em>Jędrzej</em> była powszechna w XVII-XVIII wieku. Z imieniem związane są tradycyjne <strong>andrzejki</strong> — wróżby z 29 na 30 listopada.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Jędrek, Jędruś, Andrzejek, Andy</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Andrew (ang.), Andreas (niem.), André (franc.), Andrés (hiszp.), Andrea (wł.), Андрей (ros.)</p></div>',

  "Paweł": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Paweł pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>paulus</em> oznaczającego <strong>„mały"</strong>, „skromny". Było to popularne imię w starożytnym Rzymie, znane szczególnie dzięki świętemu Pawłowi Apostołowi.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię Paweł dokumentowane jest od <strong>XII wieku</strong> (łac. <em>Paulus</em>, 1155). Dało początek licznym polskim nazwom miejscowym i nazwiskom: Pawlak, Paszek, Pawłów.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Pawełek, Pawcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Paul (ang., niem., franc.), Pablo (hiszp.), Paolo (wł.), Pál (węg.), Павел (ros.)</p></div>',

  "Michał": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Michał pochodzi z języka <strong>hebrajskiego</strong> — od pytania retorycznego <em>Mikha-El</em> oznaczającego <strong>„któż jest jak Bóg?"</strong>. Nosił je archanioł Michał — obrońca i wojownik niebieski.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozpowszechniło się w Polsce wraz z chrześcijaństwem. Dziś jest jednym z najpopularniejszych imion męskich — nosi je blisko pół miliona Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Michałek, Michaś, Misiek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Michael (ang., niem.), Michel (franc.), Miguel (hiszp.), Michele (wł.), Mikhail (ros.), Mihail (rum.)</p></div>',

  "Ewa": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Ewa pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>hawwah</em> oznaczającego <strong>„życie"</strong> lub „dawczyni życia". Według Biblii Ewa była pierwszą kobietą — matką całej ludzkości.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno z najstarszych imion chrześcijańskich, znane z Księgi Rodzaju. W Polsce przez wieki należało do czołowych imion żeńskich — dziś nosi je blisko pół miliona Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ewka, Ewcia, Ewusia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Eve (ang.), Eva (niem., hiszp., wł.), Ève (franc.), Eva (ros.), Éva (węg.)</p></div>',

  "Barbara": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Barbara pochodzi z języka <strong>greckiego</strong> — od słowa <em>barbaros</em> oznaczającego „obcy", „cudzoziemiec". W starożytności Grecy tak nazywali wszystkich nie mówiących po grecku.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię znane od wieków. Patronką jest <strong>święta Barbara z Nikomedii</strong> — legendarna męczennica z III/IV wieku, której wspomnienie obchodzone jest 4 grudnia. Z jej imieniem związane są liczne polskie przysłowia pogodowe.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Basia, Baśka, Basieńka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Barbara (ang., niem., franc., hiszp.), Barbora (czes., słowac.), Warwara (ros., ukr.)</p></div>',

  "Jan": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jan pochodzi z języka <strong>hebrajskiego</strong> — od imienia <em>Johanan</em> oznaczającego <strong>„Bóg jest łaskawy"</strong>. Do Polski dotarło przez grekę i łacinę.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno z najstarszych i najpopularniejszych imion w Polsce — dokumentowane od <strong>1012 roku</strong> (jako <em>Ioannes</em>), od <strong>1161 roku</strong> w formie Jan. Przez wieki należało do najczęstszych imion męskich w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Janek, Jasiek, Jaś, Jaszko</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>John, Ian (ang.), Jean (franc.), Juan (hiszp.), Johannes (niem.), Giovanni (wł.), Иван (ros.)</p></div>',

  "Marcin": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Marcin pochodzi z języka <strong>łacińskiego</strong> — od imienia <em>Martinus</em>, które wywodzi się od imienia boga wojny <strong>Marsa</strong>. Oznacza dosłownie „należący do Marsa".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię poświadczone od <strong>1393 roku</strong> w księgach krakowskich. Popularność zawdzięcza kultowi świętego Marcina z Tours — jego święto (11 listopada) jest w Polsce tradycyjnie obchodzone rogalami świętomarcińskimi.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Marcinek, Martuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Martin (ang., niem., franc., hiszp.), Martino (wł.), Márton (węg.), Мартин (ros.)</p></div>',

  "Magdalena": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Magdalena pochodzi od nazwy miejscowości <strong>Magdala</strong> nad Jeziorem Galilejskim. Dosłownie oznacza „kobieta z Magdali". Imię ściśle związane z postacią <strong>Marii Magdaleny</strong> z Nowego Testamentu.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię trafiło do Polski wraz z chrześcijaństwem. Dziś nosi je ponad 430 tysięcy Polek — jest ósmym najpopularniejszym imieniem żeńskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Magda, Madzia, Lena</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Madeleine (franc.), Madeline (ang.), Magdalena (niem., hiszp.), Maddalena (wł.), Magdaléna (czes.)</p></div>',

  "Jakub": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jakub pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>Yaakov</em> (יַעֲקֹב), co oznacza „trzymający za piętę" lub „ten, który zastępuje". W Biblii Jakub był synem Izaaka i wnukiem Abrahama — praojciec dwunastu plemion Izraela.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozpowszechniło się w Polsce dzięki dwóm apostołom noszącym to imię: Jakubowi Starszemu i Jakubowi Młodszemu. Dziś jest jednym z najpopularniejszych imion dla chłopców.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Kuba, Kubek, Kubuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>James, Jacob (ang.), Jacques (franc.), Jaime (hiszp.), Giacomo (wł.), Jakob (niem.), Яков (ros.)</p></div>',

  "Elżbieta": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Elżbieta pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>Eliszeba</em> (אלשבת) oznaczającego <strong>„Bóg moją przysięgą"</strong> lub „mój Bóg jest pełnią". W Biblii nosiła je matka Jana Chrzciciela.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków. Noszone przez liczne królowe i cesarzowe — m.in. Elżbietę I i II królową Anglii. Dziś jest dziewiątym najpopularniejszym imieniem żeńskim w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ela, Elka, Elcia, Elunia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Elizabeth (ang.), Elisabeth (niem., franc.), Isabel (hiszp.), Elisabetta (wł.), Erzsébet (węg.), Елизавета (ros.)</p></div>',

  "Joanna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Joanna pochodzi z języka <strong>hebrajskiego</strong> — od imienia <em>Jo-hanan</em> oznaczającego <strong>„Bóg jest łaskawy"</strong>. Jest żeńską formą imienia Jan.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię obecne od <strong>XIII wieku</strong>, dokumentowane m.in. w formie Johanna i Jana. Forma Joanna pojawia się od <strong>1399 roku</strong>. Dziś nosi je ponad 400 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Joasia, Asia, Aśka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Joan, Joanne (ang.), Jeanne (franc.), Juana (hiszp.), Johanna (niem.), Giovanna (wł.)</p></div>',

  "Aleksandra": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Aleksandra pochodzi z języka <strong>greckiego</strong> — od słów <em>alexein</em> (bronić, chronić) i <em>anēr</em> (mężczyzna), co oznacza <strong>„obrończyni ludzi"</strong>. Jest żeńską formą imienia Aleksander.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię weszło w użycie w <strong>XIV wieku</strong>. Popularność zyskało m.in. dzięki powieści Henryka Sienkiewicza <em>Potop</em>, gdzie jedna z bohaterek nosiła to imię.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ola, Oleńka, Sandra, Alesia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Alexandra (ang., niem.), Alexandrine (franc.), Alejandra (hiszp.), Alessandra (wł.), Александра (ros.)</p></div>',

  "Krystyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Krystyna pochodzi z języka <strong>greckiego</strong> — od słowa <em>Christianos</em> oznaczającego <strong>„chrześcijanka"</strong>, czyli „należąca do Chrystusa". Jest żeńską formą imienia Krystian.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, noszone przez liczne święte i królowe europejskie. Szczyt popularności przypadał na lata 50.-70. XX wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Krysia, Krysieńka, Kryska</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Christina, Christine (ang., niem.), Christine (franc.), Cristina (hiszp., wł.), Кристина (ros.)</p></div>',

  "Łukasz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Łukasz pochodzi z języka <strong>greckiego</strong> — od słowa <em>Loukas</em>, nawiązującego do łacińskiego <em>lux</em> (światło) lub nazwy krainy Lukania we Włoszech. Oznacza „urodzony o świcie" lub „niosący światło".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce dzięki świętemu Łukaszowi Ewangeliście — autorowi trzeciej Ewangelii i Dziejów Apostolskich. Dziś nosi je blisko 380 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Łukaszek, Łukasz</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Lucas, Luke (ang.), Lukas (niem.), Luc (franc.), Lucas (hiszp.), Luca (wł.), Lukáš (czes.)</p></div>',

  "Mateusz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Mateusz pochodzi z języka <strong>hebrajskiego</strong> — od słów <em>mattan</em> (dar) i <em>Yah</em> (Jahwe), co oznacza <strong>„dar Boga"</strong>. Nosił je Mateusz Apostoł i Ewangelista.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W dawnej Polsce imiona Mateusz i Maciej nie były rozróżniane aż do <strong>XVI wieku</strong>. W źródłach pojawia się jako <em>Mathaeus</em> i <em>Matyjasz</em>. Dziś nosi je ponad 370 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Mateuszek, Matek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Matthew (ang.), Matthias (niem.), Mathieu (franc.), Mateo (hiszp.), Matteo (wł.), Матвей (ros.)</p></div>',

  "Monika": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Etymologia imienia Monika jest niepewna. Prawdopodobnie pochodzi z języka <strong>greckiego</strong> — od słowa <em>monos</em> (jeden, jedyny) lub <em>monaché</em> (samotna, odosobniona). Możliwe też pochodzenie afrykańskie.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię pojawia się już w <strong>XV wieku</strong> w formach Mońka i Muńka. Szerszą popularność zyskało w XIX wieku, a szczyt przypadał na lata 70. XX wieku. Patronką jest święta Monika — matka świętego Augustyna.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Moniczka, Monia, Nika</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Monica (ang., wł., hiszp.), Monique (franc.), Mónika (węg.), Моника (ros.)</p></div>',

  "Grzegorz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Grzegorz pochodzi z języka <strong>greckiego</strong> — od słowa <em>gregoreo</em> oznaczającego <strong>„być czujnym"</strong>, „czuwać". Jest polską formą łacińskiego <em>Gregorius</em>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię bardzo popularne w historii chrześcijaństwa — nosił je aż <strong>16 papieży</strong>, w tym Grzegorz I Wielki (papież, doktor Kościoła). W Polsce używane od wieków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Grześ, Grześko, Grzesiek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Gregory (ang.), Gregor (niem.), Grégoire (franc.), Gregorio (hiszp., wł.), Grigorij (ros.)</p></div>',

  "Marek": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Marek pochodzi z języka <strong>łacińskiego</strong> — wywodzi się od imienia boga wojny <strong>Marsa</strong> (<em>Mart-ico-s</em>), oznaczając „należący do Marsa". Należy do grupy starożytnych imion rzymskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce dokumentowane od <strong>XIII wieku</strong> w formach Marek, Marko, Markusz. Patronem jest <strong>święty Marek Ewangelista</strong> — autor drugiej Ewangelii, którego święto przypada 25 kwietnia.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Maruś, Mareczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Mark (ang.), Markus (niem.), Marc (franc.), Marcos (hiszp.), Marco (wł.), Марк (ros.)</p></div>',

  "Zofia": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Zofia pochodzi z języka <strong>greckiego</strong> — od słowa <em>sophía</em> (σοφία) oznaczającego <strong>„mądrość"</strong>. Jest jednym z najpiękniejszych semantycznie imion żeńskich.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, noszone przez liczne polskie księżniczki i królowe. W <strong>2022 roku</strong> było najczęściej nadawanym imieniem dla dziewczynek w Polsce. Dziś nosi je blisko 365 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Zosia, Zośka, Sonia, Sosia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Sophie, Sophia (ang., franc.), Sofia (hiszp., wł.), Sofie (niem.), София (ros.)</p></div>',

  "Stanisław": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Stanisław jest imię <strong>słowiańskie</strong> — złożone z członów <em>stani-</em> (stanąć, powstać) i <em>-sław</em> (sława), co oznacza <strong>„ten, który stanie się sławny"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno z najbardziej polskich imion — pod koniec XV wieku należało do najpopularniejszych w kraju. Patronem jest <strong>święty Stanisław ze Szczepanowa</strong> — biskup krakowski, patron Polski, męczennik (†1079).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Staś, Stasio, Stasiek, Staszek, Stach</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Stanislaus (łac., niem.), Stanislas (franc.), Estanislao (hiszp.), Szaniszló (węg.), Станислав (ros.)</p></div>',

  "Wojciech": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Wojciech jest imieniem <strong>słowiańskim</strong> — złożonym z członów <em>woj-</em> (wojownik, żołnierz) i <em>-ciech</em> (radość, pociecha), co oznacza <strong>„wojownik przynoszący radość"</strong> lub „pociecha wojska".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od <strong>X wieku</strong>. Patronem jest <strong>święty Wojciech</strong> — czeski biskup, misjonarz i męczennik (†997), patron Polski. Jego imieniny obchodzone są 23 kwietnia.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Wojtek, Wojtuś, Wojtas, Wojcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Adalbert (łac., niem.), Vojtěch (czes.) — imię w swej polskiej formie nie ma bezpośrednich odpowiedników w językach zachodnich.</p></div>',

  "Maria": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Maria pochodzi od hebrajskiego <em>Miriam</em> o niepewnej etymologii. Proponowane znaczenia to „napawa radością", „ukochana przez Boga" (z egipskiego <em>meri-jam</em>) lub „orzeźwiająca" (od hebr. <em>rawah</em>). Imię nierozerwalnie związane z Maryją — matką Jezusa.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce przez wieki imię było „zarezerwowane" dla Matki Boskiej i rzadko nadawane dzieciom — zamiast niego używano form Marianna lub Maryna. Dopiero w XIX wieku upowszechniło się jako imię świeckie. Dziś jest jednym z najpopularniejszych imion żeńskich w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Marysia, Maryśka, Maja, Mania</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Mary (ang.), Marie (franc., niem.), María (hiszp.), Maria (wł.), Мария (ros.), Mária (węg.)</p></div>',

  "Natalia": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Natalia pochodzi z języka <strong>łacińskiego</strong> — od wyrażenia <em>dies natalis</em> oznaczającego „dzień narodzin". Dawniej nadawano je dzieciom urodzonym w Boże Narodzenie.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków. W XXI wieku zyskało dużą popularność — dziś nosi je ponad 320 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Natka, Nata, Natasza</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Natalie (ang.), Nathalie (franc.), Natalia (niem., hiszp., wł.), Наталья (ros.)</p></div>',

  "Julia": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Julia pochodzi ze starożytnego <strong>Rzymu</strong> — od nazwy rodu Juliuszów (<em>Iulii</em>). Znaczenie łączone z łacińskim <em>Iovis</em> (Jowisz) lub słowem oznaczającym „burzę".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Przez wiele lat (2001–2012, 2017, 2020) Julia była <strong>najczęściej nadawanym imieniem dziewczynkom w Polsce</strong>. Dziś nosi je ponad 310 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Julka, Julcia, Jula</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Julie, Juliette (franc.), Giulia (wł.), Юлия (ros.), Júlia (węg.)</p></div>',

  "Teresa": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Teresa pochodzi prawdopodobnie z języka <strong>greckiego</strong> — od nazwy wyspy <em>Thera</em> (dziś Santoryn) lub od słowa <em>therizo</em> (zbierać plony, żąć). Etymologia nie jest w pełni wyjaśniona.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię pojawiło się w <strong>XVII wieku</strong>. Patronkami są m.in. <strong>święta Teresa z Ávili</strong> — doktor Kościoła i mistyczka oraz <strong>święta Teresa z Kalkuty</strong> (Matka Teresa) — laureatka Pokojowej Nagrody Nobla.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Tereska, Tesia, Resa</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Theresa (ang., niem.), Thérèse (franc.), Theresa (hiszp.), Тереза (ros.), Tereza (czes.)</p></div>',

  "Karolina": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Karolina jest żeńską formą imienia Karol, które pochodzi ze <strong>starogermańskiego</strong> słowa <em>karl</em> oznaczającego „wolny mężczyzna", „mąż" lub „wojownik".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię popularne w Polsce od XVIII wieku, noszone przez liczne europejskie księżniczki i królowe. Dziś nosi je blisko 300 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Karo, Karolka, Lina</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Caroline (ang., franc.), Carolina (hiszp., wł.), Karoline (niem.), Каролина (ros.)</p></div>',

  "Marta": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Marta pochodzi z języka <strong>aramejskiego</strong> — od słowa <em>marta</em> oznaczającego <strong>„pani domu"</strong>, „gospodarcza". W Biblii Marta była siostrą Marii i Łazarza.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków dzięki tradycji chrześcijańskiej. Popularne szczególnie w XX i XXI wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Martusia, Marteczka, Martunia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Martha (ang., niem.), Marthe (franc.), Marta (hiszp., wł.), Марта (ros.)</p></div>',

  "Danuta": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Danuta pochodzi prawdopodobnie z języka <strong>litewskiego</strong> — od słowa <em>danutė</em> łączącego znaczenia „niebo" i „córka". Możliwe też pochodzenie od łacińskiego <em>donata</em> — „darowana przez Boga".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane od <strong>XIV wieku</strong>. Znane m.in. z powieści Henryka Sienkiewicza <em>Krzyżacy</em>, gdzie nosiła je córka księcia Kiejstuta.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Danka, Danusia, Danuśka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Imię typowo polskie, bez bezpośrednich odpowiedników w innych językach.</p></div>',

  "Mariusz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Mariusz pochodzi z języka <strong>łacińskiego</strong> — od starożytnego rodu Mariuszów (<em>Marius</em>), wywodzącego się od imienia boga wojny <strong>Marsa</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię używane od <strong>XIII wieku</strong>. Dziś nosi je blisko 285 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Mariuszek, Marian</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Marius (ang., niem., franc.), Mario (hiszp., wł.), Máriusz (węg.), Марио (ros.)</p></div>',

  "Dariusz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Dariusz pochodzi z języka <strong>perskiego</strong> — od imienia <em>Dārayavahuš</em> złożonego z elementów oznaczających „posiadać" i „dobro", co razem daje znaczenie <strong>„posiadający dobro"</strong> lub „bogaty w dobra".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane z historii starożytnej dzięki trzem perskim królom Dariuszom. W Polsce w użyciu od co najmniej <strong>XVIII wieku</strong>, choć szeroką popularność zyskało dopiero w XX wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Darek, Daruś, Daro</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Darius (ang., niem.), Daire (franc.), Darío (hiszp.), Дарий (ros.)</p></div>',

  "Beata": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Beata pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>beatus</em> oznaczającego <strong>„błogosławiona"</strong>, „szczęśliwa", „przynosząca szczęście". Jest żeńską formą imienia Beat.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, szczyt popularności przypadał na lata 60.-80. XX wieku. Dziś nosi je blisko 280 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Beatka, Becia, Beaśka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Beatrice, Beatrix (ang.), Beate (niem.), Béatrice (franc.), Beatriz (hiszp.), Беата (ros.)</p></div>',

  "Maciej": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Maciej pochodzi z języka <strong>hebrajskiego</strong> — jest polską formą aramejskiego <em>Matatjahu</em> (מַתִּתְיָהוּ), co oznacza <strong>„dar Boga"</strong> lub „Bóg jest łaskawy". Wywodzi się z elementów: <em>mattan</em> (dar) i <em>Yah</em> (Jahwe).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane od <strong>1201 roku</strong>. Nosił je Maciej Apostoł — wybrany przez uczniów Jezusa na miejsce Judasza Iskarioty. Imię znane z polskiego folkloru i literatury ludowej.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Maciek, Maciuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Matthias (ang., niem.), Matías (hiszp.), Mattia (wł.), Матвей (ros.), Matěj (czes.)</p></div>',

  "Dorota": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Dorota pochodzi z języka <strong>greckiego</strong> — złożone z elementów <em>doron</em> (dar) i <em>theos</em> (Bóg), co oznacza <strong>„dar Boży"</strong>. Jest żeńskim odpowiednikiem imienia Doroteusz — podobne znaczenie ma też imię Teodora.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane od <strong>1385 roku</strong>. Dziś nosi je blisko 270 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Dorotka, Dorcia, Dosia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Dorothy (ang.), Dorothée (franc.), Dorotea (hiszp., wł.), Dorottya (węg.), Дорота (ros.)</p></div>',

  "Rafał": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Rafał pochodzi z języka <strong>hebrajskiego</strong> — od słów <em>rofe</em> (uzdrowiciel) i <em>El</em> (Bóg), co oznacza <strong>„Bóg uzdrawia"</strong>. Nosił je archanioł Rafał — patron lekarzy i aptekarzy.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię zyskało popularność w Polsce w końcu lat 30. XX wieku dzięki powieści Tadeusza Dołęgi-Mostowicza <em>Znachor</em> (1937), której bohater miał na imię Rafał Wilczur.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Rafałek, Rafcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Raphael (ang., niem., franc.), Rafael (hiszp., port.), Raffaele (wł.), Рафаил (ros.)</p></div>',

  "Robert": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Robert pochodzi ze <strong>starogermańskiego</strong> — złożone z elementów <em>hrod</em> (sława, chwała) i <em>beraht</em> (jasny, błyszczący), co oznacza <strong>„sławny blaskiem"</strong> lub „jaśniejący chwałą".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię bardzo popularne w średniowiecznej Europie, noszone przez licznych królów — m.in. Roberta Bruce&#39;a króla Szkocji. W Polsce używane od wieków, szczyt popularności przypadał na lata 60.-80. XX wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Robek, Robi, Robertek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Robert (ang., niem., franc., hiszp.), Roberto (wł., hiszp.), Роберт (ros.)</p></div>',

  "Kamil": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Kamil pochodzi z języka <strong>łacińskiego</strong> — od <em>Camillus</em>, co oznaczało „pomocnik kapłana" lub „szlachetnie urodzony chłopiec". Możliwe też pochodzenie etruskie.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków. Patronem jest <strong>święty Kamil de Lellis</strong> — włoski zakonnik, założyciel zakonu Kamilianów, patron chorych i personelu medycznego.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Kamilek, Kamilus</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Camille (franc.), Camilo (hiszp.), Camillo (wł.), Camil (rum.), Камилл (ros.)</p></div>',

  "Zbigniew": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Zbigniew jest imieniem <strong>słowiańskim</strong> — złożonym z elementów <em>Zby-</em> (pozbyć się, uwolnić) i <em>-gniew</em> (gniew, złość), co oznacza <strong>„ten, kto pozbył się gniewu"</strong>. Pierwotna forma brzmiała <em>Zbygniew</em>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno z najstarszych polskich imion słowiańskich — pod koniec XV wieku nosiło je ok. 1000 osób w Polsce. Nosił je m.in. kardynał Zbigniew Oleśnicki (1389–1455).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Zbyszek, Zbysio, Zbych</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Imię typowo polskie, bez bezpośrednich odpowiedników w innych językach.</p></div>',

  "Szymon": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Szymon pochodzi z języka <strong>hebrajskiego</strong> — od imienia <em>Shim\'on</em> (שמעון) oznaczającego <strong>„Bóg wysłuchał"</strong>. Nosił je jeden z dwunastu apostołów Jezusa — Szymon Piotr.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków dzięki tradycji chrześcijańskiej. Dziś przeżywa renesans — w 2017 roku było czwartym najczęściej nadawanym imieniem chłopcom w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Szymek, Szymonek, Szymuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Simon (ang., niem., franc.), Simón (hiszp.), Simone (wł.), Симон (ros.)</p></div>',

  "Dawid": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Dawid pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>dawid</em> (דָּוִד) oznaczającego <strong>„ukochany"</strong> lub „przyjaciel". Nosił je jeden z największych królów Izraela — Dawid, autor Psalmów.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków dzięki tradycji biblijnej. W XXI wieku zyskało dużą popularność — dziś nosi je blisko 240 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Dawidek, Dawcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>David (ang., niem., franc., hiszp.), Davide (wł.), Давид (ros.)</p></div>',

  "Jolanta": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jolanta pochodzi z języka <strong>greckiego</strong> — od słów <em>ion</em> (fiołek) i <em>anthos</em> (kwiat), co oznacza <strong>„kwiat fioletowy"</strong> lub „fiołek". Jest polską formą imienia Yolanda.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię używane od <strong>XIII wieku</strong>, początkowo w formie Jolenta. Patronką jest <strong>błogosławiona Jolanta</strong> — córka króla Węgier, księżna polska (1244–1304).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Jola, Jolka, Jolantuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Yolanda (ang., hiszp.), Yolande (franc.), Iolanda (wł.), Иоланта (ros.)</p></div>',

  "Kacper": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Kacper pochodzi z języka <strong>perskiego</strong> — od słowa <em>ganzabara</em> oznaczającego <strong>„strażnik skarbu"</strong>. Złożone z <em>ganzah</em> (skarb) i <em>barah</em> (nieść, strzec).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię tradycyjnie przypisywane jednemu z <strong>Trzech Króli</strong> (Mędrców ze Wschodu). W Polsce używane od <strong>połowy XIV wieku</strong>. Imieniny Kacpra obchodzone są 6 stycznia — w Święto Trzech Króli.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Kacperek, Kacpruś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Casper (ang., niem.), Gaspard (franc.), Gaspar (hiszp., port.), Jasper (niem., nid.)</p></div>',

  "Hanna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Hanna pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>hannāh</em> oznaczającego <strong>„łaska"</strong> lub „pełna łaski". Jest starszą formą imienia Anna, bliższą oryginałowi biblijnemu.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Biblii Hanna była matką proroka Samuela. W Polsce imię dokumentowane od <strong>1311 roku</strong>. Dziś nosi je ponad 230 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Hania, Hanka, Hanusia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Hannah (ang., niem.), Hanne (skandynaw.), Hana (czes.), Ханна (ros.)</p></div>',

  "Zuzanna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Zuzanna pochodzi z języka <strong>hebrajskiego</strong> — od słowa <em>szoszana</em> (שׁוֹשַׁנָּה) oznaczającego <strong>„lilia"</strong>. Słowo wywodzi się prawdopodobnie z egipskiego <em>seszen</em> — lotos.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane od <strong>1265 roku</strong>. W Biblii Zuzanna to bohaterka Księgi Daniela — piękna i cnotliwa kobieta, fałszywie oskarżona przez starców. Dziś nosi je ponad 230 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Zuzia, Zuza, Zuzka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Susan, Susannah (ang.), Suzanne (franc.), Zuzana (czes.), Zsuzsanna (węg.)</p></div>',

  "Iwona": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Iwona pochodzi z języka <strong>germańskiego</strong> lub celtyckiego — jest żeńską formą imienia Iwo, wywodzącego się od germańskiego <em>iv</em> (cis). Możliwe też pochodzenie z celtyckiego.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię stosunkowo nowe w Polsce — upowszechniło się w <strong>XX wieku</strong>. Znane m.in. z dramatu Witolda Gombrowicza <em>Iwona, księżniczka Burgunda</em>. W latach 60.-80. otrzymało je ok. 180 tysięcy kobiet.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Iwonka, Iwcia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Yvonne (franc.), Yvonne (ang., niem.), Ivona (czes.)</p></div>',

  "Jacek": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jacek wywodzi się od greckiego <em>Hyakinthos</em> — imienia mitologicznego młodzieńca, ulubieńca Apollina, od którego krwi wyrosł kwiat hiacynt. Oznacza dosłownie <strong>„hiacynt"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce znane od <strong>XII wieku</strong>. Patronem jest <strong>święty Jacek Odrowąż</strong> (1183–1257) — dominikanin, misjonarz, zwany „apostołem Północy". Imię rozkwitło szczególnie w XVII wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Jacuś, Jaceczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Jacinto (hiszp., port.), Giacinto (wł.), Jácint (węg.) — imię Jacek nie ma pełnego odpowiednika w językach zachodnich.</p></div>',

  "Halina": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Halina pochodzi z języka <strong>greckiego</strong> — od słowa <em>galene</em> (γαλήνη) oznaczającego <strong>„spokój"</strong>, „cisza morska", „dobrobyt". Jest polską formą imienia Galina.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronką jest święta Halina z Koryntu — dziewica i męczennica (†258). Zdrobnienie <strong>Halka</strong> zyskało popularność dzięki operze Stanisława Moniuszki i zaczęło funkcjonować jako samodzielne imię.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Halka, Haleczka, Halunia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Galina (ros., ukr.), Helena (łac. forma podstawowa)</p></div>',

  "Paulina": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Paulina pochodzi z języka <strong>łacińskiego</strong> — jest żeńską formą imienia Paweł (<em>Paulus</em>), oznaczającego <strong>„mała"</strong>, „skromna". Wywodzi się od starożytnego rodu Emiliuszów-Paulinów.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków, szczyt popularności przypadał na lata 90. XX wieku. Dziś nosi je ponad 220 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Paula, Paulinka, Pauleczka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Pauline (ang., franc., niem.), Paulina (hiszp., wł.), Паулина (ros.)</p></div>',

  "Grażyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Grażyna pochodzi z języka <strong>litewskiego</strong> — od słowa <em>graži</em> oznaczającego <strong>„piękna"</strong>. Jest imieniem literackim — zostało wymyślone przez Adama Mickiewicza dla bohaterki jego poematu <em>Grażyna</em> (1823).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Choć wymyślone przez Mickiewicza, imię szybko przyjęło się w Polsce i stało się powszechnie używane. Szczyt popularności przypadał na lata 50.-70. XX wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Grażynka, Grażka, Grasia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Imię typowo polskie, bez bezpośrednich odpowiedników w innych językach.</p></div>',

  "Jerzy": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jerzy pochodzi z języka <strong>greckiego</strong> — od słów <em>ge</em> (ziemia) i <em>ergon</em> (praca), co oznacza <strong>„rolnik"</strong> lub „ten, kto uprawia ziemię". Jest polską formą greckiego Georgios.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Popularność imienia zawdzięczamy kultowi <strong>świętego Jerzego</strong> — legendarnego rycerza i męczennika, który pokonał smoka. Jego święto przypada 23 kwietnia. W Polsce imię używane od wieków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Jurek, Jureczek, Jerzyk</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>George (ang.), Georg (niem.), Georges (franc.), Jorge (hiszp.), Giorgio (wł.), György (węg.), Юрий (ros.)</p></div>',

  "Jadwiga": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jadwiga pochodzi ze <strong>starogermańskiego</strong> — złożone z elementów <em>hadu</em> i <em>wig</em>, oba oznaczające „walkę" lub „bitwę". Oznacza dosłownie <strong>„wojowniczka"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane od <strong>1208 roku</strong>. Patronkami są <strong>święta Jadwiga Śląska</strong> (patronka Polski i Niemiec) oraz <strong>święta Jadwiga Królowa</strong> — pierwsza kobieta koronowana na króla Polski (†1399).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Jadzia, Jaga, Jagoda, Iga, Jagienka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Hedwig (niem.), Hedvika (czes.), Edvige (wł.)</p></div>',

  "Justyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Justyna pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>iustus</em> oznaczającego <strong>„sprawiedliwa"</strong>, „praworządna". Jest żeńską formą imienia Justyn.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię znane w Polsce od wieków dzięki tradycji chrześcijańskiej. Patronką jest święta Justyna — męczennica z IV wieku. Dziś nosi je ponad 215 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Justynka, Justecia, Justa</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Justine (franc., niem.), Justina (hiszp.), Giustina (wł.), Устинья (ros.)</p></div>',

  "Wiktoria": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Wiktoria pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>victoria</em> oznaczającego <strong>„zwycięstwo"</strong>. W mitologii rzymskiej Wiktoria była boginią zwycięstwa i chwały.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię zyskało wielką popularność w XXI wieku — w 2009 roku było czwartym najczęściej nadawanym imieniem dziewczynkom. Noszone przez królową Wiktorię (1819–1901) — najdłużej panującą monarchinię Wielkiej Brytanii.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Wika, Wikta, Wikcia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Victoria (ang., hiszp., wł.), Victoire (franc.), Viktoria (niem.), Виктория (ros.)</p></div>',

  "Bartosz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Bartosz jest polską formą imienia <strong>Bartłomiej</strong>, które pochodzi z języka aramejskiego — od <em>bar-Talmaj</em>, czyli „syn Talmaja". Bartłomiej był jednym z dwunastu apostołów Jezusa.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane od <strong>1216 roku</strong>. Po wiekach zapomnienia przeżyło odrodzenie pod koniec XX wieku. Dziś nosi je ponad 200 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Bartek, Bartuś, Barto</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Bartholomew (ang.), Bartholomäus (niem.), Barthélemy (franc.), Bartolomé (hiszp.), Варфоломей (ros.)</p></div>',

  "Artur": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Artur pochodzi z języka <strong>celtyckiego</strong> — od elementów <em>art</em> (niedźwiedź) i <em>ur</em> (młody, piękny), co oznacza <strong>„młody niedźwiedź"</strong> lub „szlachetny". Alternatywnie od celtyckiego <em>ard</em> — „wysoki", „szlachetny".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozsławione przez legendarnego <strong>króla Artura</strong> — bohatera średniowiecznych romansów rycerskich o Okrągłym Stole. W Polsce używane od wieków, dziś nosi je blisko 200 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Arek, Arturek, Artur</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Arthur (ang., franc.), Arthur (niem.), Arturo (hiszp., wł.), Артур (ros.)</p></div>',

  "Maja": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Maja pochodzi z języka <strong>greckiego</strong> — od słowa <em>maia</em> (μαῖα) oznaczającego <strong>„dobra matka"</strong>, „pani", „mamka". W mitologii greckiej Maja była najstarszą z Plejad — nimf córek Atlasa, matką Hermesa.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię bardzo popularne w XXI wieku — w 2017 roku zajmowało 5. miejsce wśród imion nadawanych dziewczynkom. Znane też z kultowej bajki animowanej <em>Pszczółka Maja</em>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Majka, Majeczka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Maya (ang.), Maya (franc., hiszp.), Maia (wł., port.), Майя (ros.)</p></div>',

  "Jarosław": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Jarosław jest imieniem <strong>słowiańskim</strong> — złożonym z elementów <em>jary</em> (silny, krzepki, żywotny) i <em>-sław</em> (sława, chwała), co oznacza <strong>„ten o silnej sławie"</strong> lub „wsławiony siłą".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno ze starych polskich imion słowiańskich — znane od wieków. Nosił je m.in. <strong>Jarosław Mądry</strong> (978–1054) — wielki książę kijowski, jeden z najwybitniejszych władców Rusi. Pod koniec XV wieku nosiło je ok. 700 osób w Polsce.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Jarek, Jaruś, Jareczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Jaroslav (czes., słowac.), Yaroslav (ukr.), Ярослав (ros.) — imię typowo słowiańskie.</p></div>',

  "Tadeusz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Tadeusz pochodzi z języka <strong>aramejskiego</strong> lub hebrajskiego — tradycyjnie interpretowane jako <strong>„odważny"</strong> lub „chwalebny wyznawca". Związane z imieniem apostoła Judy Tadeusza.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce szczególnie popularny dzięki eposowi Adama Mickiewicza <em>Pan Tadeusz</em> (1834). Wybitni nosiciele to <strong>Tadeusz Kościuszko</strong> — bohater walk o niepodległość Polski i USA, oraz artysta awangardowy <strong>Tadeusz Kantor</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Tadek, Tadzio, Tadzik, Tadeuszek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Thaddeus (ang.), Thaddäus (niem.), Taddeo (wł.), Tadeo (hiszp.), Tadeáš (czes.)</p></div>',

  "Sebastian": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Sebastian pochodzi z języka <strong>greckiego</strong> — od słowa <em>sebastos</em> oznaczającego <strong>„czcigodny"</strong>, „godny szacunku". Wywodzi się od nazwy miejscowej Sebastia (dzisiejsze Sivas w Turcji).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Popularność imienia zawdzięczamy kultowi <strong>świętego Sebastiana</strong> — oficera gwardii cesarskiej i męczennika (†ok. 288), patrona żołnierzy i sportowców. W Polsce szczyt popularności przypadł na lata 90. XX w.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Sebek, Sebcio, Sebastianek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Sebastian (ang., niem., hiszp.), Sébastien (franc.), Sebastiano (wł.), Себастьян (ros.)</p></div>',

  "Renata": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Renata pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>renata</em> oznaczającego <strong>„odrodzona"</strong> (od <em>re-</em> znów + <em>natus</em> urodzony). Nawiązuje do chrześcijańskiej idei odrodzenia przez chrzest.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Do Polski imię dotarło w XVII wieku pod wpływem francuskim. Dziś nosi je blisko 186 tysięcy Polek. Znana nosicielka to słynna włoska sopranistka <strong>Renata Tebaldi</strong> (1922–2004).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Rena, Renatka, Renia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Renée (franc.), Renata (wł., hiszp.), Renate (niem.), Рената (ros.)</p></div>',

  "Agata": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Agata pochodzi z języka <strong>greckiego</strong> — od słowa <em>agathos</em> (ἀγαθός) oznaczającego <strong>„dobra"</strong>, „szlachetna". Rdzeń ten pojawia się m.in. w słowie „agat" — nazwie kamienia szlachetnego.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię dokumentowane od <strong>XIII wieku</strong>. Patronką jest <strong>święta Agata z Sycylii</strong> — dziewica i męczennica (†ok. 251), patronka pielęgniarek i straży pożarnej. Imieniny 5 lutego.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Agatka, Aga, Agateczka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Agatha (ang., niem.), Agathe (franc.), Ágata (hiszp.), Agata (wł., ros.)</p></div>',

  "Damian": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Damian pochodzi z języka <strong>greckiego</strong> — od słowa <em>daman</em> (δαμάω) oznaczającego <strong>„poskramiać"</strong>, „zwyciężać". Może też nawiązywać do bogini Damii czczonej w Epidaurze.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronem jest <strong>święty Damian</strong> — lekarz i męczennik, brat Kosmy (patroni lekarzy i farmaceutów, †ok. 303). Belgijski <strong>ojciec Damian De Veuster</strong> (1840–1889) opiekował się trędowatymi na Hawajach, beatyfikowany w 1995 r.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Damianek, Damek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Damian (ang.), Damien (franc.), Damiano (wł.), Damián (hiszp.), Дамиан (ros.)</p></div>',

  "Sylwia": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Sylwia pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>silva</em> oznaczającego <strong>„las"</strong>, „gaj". Nawiązuje do mitologicznej <strong>Rei Sylwii</strong> — matki Romulusa i Remusa, legendarnych założycieli Rzymu.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Znane z mitologii i historii Rzymu. W Polsce popularność zyskało w XX wieku. Nosi je m.in. <strong>królowa Sylwia Szwecji</strong> (ur. 1943) oraz polska piosenkarka <strong>Sylwia Grzeszczak</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Sylwcia, Sylweczka, Sylwa</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Sylvia (ang., niem.), Sylvie (franc.), Silvia (wł., hiszp.), Сильвия (ros.)</p></div>',

  "Sławomir": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Sławomir jest imieniem <strong>słowiańskim</strong> — złożonym z elementów <em>sław-</em> (sława, chwała) i <em>-mir</em> (pokój, spokój), co oznacza <strong>„ten, kto zdobywa sławę pokojem"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Znane w Polsce od wieków. Największą popularność zyskało w latach 50.–60. XX w. Wybitnym przedstawicielem jest pisarz i dramaturg <strong>Sławomir Mrożek</strong>. Żeńską formą jest Sławomira.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Sławek, Sław, Sławuś</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Slavomír (czes., słowac.), Slavomir (chorwac.) — imię typowo słowiańskie.</p></div>',

  "Patryk": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Patryk pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>patricius</em> oznaczającego <strong>„patrycjusz"</strong>, „szlachetnie urodzony". Jest polską formą imienia Patrycjusz.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronem jest <strong>święty Patryk</strong> (ok. 389–461) — apostoł Irlandii, jeden z jej patronów. Jego święto (17 marca) obchodzone jest na całym świecie jako Dzień Świętego Patryka.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Patrycek, Patek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Patrick (ang., franc.), Patrik (szw., czes.), Patricio (hiszp.), Patrizio (wł.)</p></div>',

  "Urszula": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Urszula pochodzi z języka <strong>łacińskiego</strong> — jest zdrobnieniem od <em>ursa</em> (niedźwiedzica), co oznacza <strong>„mała niedźwiedzica"</strong>. Forma nawiązuje do konstelacji Małej Niedźwiedzicy.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce dokumentowane od <strong>1367 roku</strong>. Patronkami są <strong>święta Urszula z Kolonii</strong> (†ok. 383) oraz <strong>Urszula Ledóchowska</strong> — polska zakonnica i działaczka charytatywna, kanonizowana w 2003 r.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ula, Ulka, Urszulka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Ursula (ang., niem.), Ursule (franc.), Úrsula (hiszp.), Orsolya (węg.)</p></div>',

  "Antoni": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Antoni pochodzi z języka <strong>łacińskiego</strong> — od starożytnego rodu Antoniuszów (<em>Antonius</em>). Znaczenie niepewne, może wywodzić się z greckiego <em>anthos</em> (<strong>„kwiat"</strong>) lub od etruskiego imienia własnego.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronem jest <strong>święty Antoni Padewski</strong> (1195–1231) — franciszkanin, cudotwórca, patron Portugalii i osób szukających zagubionych przedmiotów. Jego imieniny obchodzone są 13 czerwca.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Antek, Anteczek, Toni</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Anthony (ang.), Antoine (franc.), Anton (niem.), Antonio (wł., hiszp.), Антон (ros.)</p></div>',

  "Filip": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Filip pochodzi z języka <strong>greckiego</strong> — złożone z <em>philos</em> (przyjaciel) i <em>hippos</em> (koń), co oznacza <strong>„miłośnik koni"</strong>. Imię spopularyzował Filip II Macedoński — ojciec Aleksandra Wielkiego.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronem jest <strong>Filip Apostoł</strong> — jeden z dwunastu uczniów Jezusa. W Polsce imię znane od wieków, dziś nosi je ponad 175 tysięcy Polaków.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Filipek, Filio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Philip (ang.), Philippe (franc.), Philipp (niem.), Felipe (hiszp.), Filippo (wł.), Филипп (ros.)</p></div>',

  "Roman": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Roman pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>Romanus</em> oznaczającego <strong>„Rzymianin"</strong>, „pochodzący z Rzymu". Nawiązuje do starożytnego Imperium Rzymskiego i jego kultury.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię znane od wieków. Wybitni nosiciele to reżyser <strong>Roman Polański</strong>, polityk <strong>Roman Dmowski</strong> oraz święty Roman — pustelnik z VII wieku. Żeńską formą jest Romana.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Romek, Romcio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Roman (ang., niem., franc.), Romano (wł.), Román (hiszp.), Роман (ros., ukr.)</p></div>',

  "Mirosław": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Mirosław jest imieniem <strong>słowiańskim</strong> — złożonym z elementów <em>miro-</em> (pokój) i <em>-sław</em> (sława, chwała), co oznacza <strong>„ten, kto wsławia pokój"</strong> lub „sławny pokojem".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Jedno ze starych imion słowiańskich — relikt pogańskich imion używanych przez Słowian we wczesnym średniowieczu. W Polsce popularne szczególnie w połowie XX wieku. Żeńską formą jest Mirosława.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Mirek, Mir, Mirko, Mirosz</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Miroslav (czes., słowac., chorwac.), Мирослав (ros.) — imię typowo słowiańskie.</p></div>',

  "Janusz": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Janusz jest polską formą imienia <strong>Jan</strong>, wywodzącego się z hebrajskiego <em>Johanan</em> — <strong>„Bóg jest łaskawy"</strong>. Pierwotnie zdrobnienie od Jana, z czasem usamodzielniło się jako odrębne imię.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce dokumentowane od <strong>1145–1178 roku</strong>. Wybitnym nosicielem jest pedagog i pisarz <strong>Janusz Korczak</strong> — bohater, który zginął wraz ze swoimi wychowankami w Treblince w 1942 r.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Januszek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Imię charakterystyczne dla języka polskiego. Pokrewne: Janus (łac.), Johannes (niem.), Jánuš (słowac.)</p></div>',

  "Daniel": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Daniel pochodzi z języka <strong>hebrajskiego</strong> — złożone z <em>Dan</em> (sądzić) i <em>El</em> (Bóg), co oznacza <strong>„Bóg jest moim sędzią"</strong>. Jest imieniem jednego z czterech wielkich proroków biblijnych.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Biblii Daniel to prorok, którego Bóg uchronił w lwiej jamie. W Polsce imię znane od wieków, dziś nosi je ponad 170 tysięcy Polaków. Żeńską formą jest Daniela.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Danek, Danelek, Danio</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Daniel (ang., franc., niem., hiszp.), Daniele (wł.), Даниил (ros.)</p></div>',

  "Patrycja": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Patrycja pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>patricius</em> oznaczającego <strong>„patrycjuszka"</strong>, „szlachetnie urodzona". Jest żeńską formą imion Patrycjusz, Patrycy i Patryk.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronkami są święta Patrycja z Nikomedii (13 marca) i święta Patrycja z Neapolu (25 sierpnia). W Polsce dziś nosi je ponad 169 tysięcy kobiet.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Patka, Patrycyjka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Patricia (ang., niem., hiszp., franc.), Patrícia (port.), Патриция (ros.)</p></div>',

  "Oliwia": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Oliwia pochodzi z języka <strong>łacińskiego</strong> — od słowa <em>oliva</em> oznaczającego <strong>„drzewo oliwne"</strong> lub „owoc oliwki". Symbol pokoju i płodności znany ze starożytności.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię mogło zostać stworzone przez <strong>Williama Szekspira</strong> dla bohaterki komedii <em>Wieczór Trzech Króli</em>. W Polsce popularność rosła od lat 80. XX w., od 2022 roku jest w pierwszej dziesiątce imion nadawanych dziewczynkom.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ola, Oliwka, Oliweczka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Olivia (ang., wł., franc., niem., hiszp.) — imię popularne na całym świecie; od 2019 r. najczęściej nadawane w USA.</p></div>',

  "Karol": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Karol pochodzi z języka <strong>frankijskiego</strong> — od starogermańskiego <em>karl</em> oznaczającego <strong>„mężczyzna"</strong>, „mąż", „człowiek wolny". Spopularyzowane przez imię cesarza Karola Wielkiego.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Do Polski dotarło wraz z chrześcijaństwem. Najsłynniejszym polskim Karolem był <strong>Karol Wojtyła</strong> — papież Jan Paweł II. Zdrobnienie <em>Lolek</em> to potoczna forma imienia.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Lolek, Karolek, Karoleczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Charles (franc., ang.), Karl (niem.), Carlo (wł.), Carlos (hiszp.), Károly (węg.), Карл (ros.)</p></div>',

  "Emilia": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Emilia pochodzi z języka <strong>łacińskiego</strong> — od starożytnego rodu <em>Aemilii</em>. Wywodzi się od słowa <em>aemulus</em> oznaczającego <strong>„rywalizująca"</strong>, „pilna", „gorliwa".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce szczególnie znana dzięki postaci <strong>Emilii Plater</strong> (1806–1831) — bohaterki powstania listopadowego, „polskiej Joanny d’Arc". W XXI wieku imię powróciło do łask — w 2017 r. zajmowało 14. miejsce wśród imion nadawanych dziewczynkom.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Emilka, Emi, Emileczka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Emily (ang.), Émilie (franc.), Emilie (niem., czes.), Emilia (hiszp., wł., ros.)</p></div>',

  "Przemysław": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Przemysław jest imieniem <strong>słowiańskim</strong> — złożonym z elementów <em>przemysł</em> (spryt, fortel) i <em>-sław</em> (sława), co oznacza <strong>„ten, kto zdobywa sławę sprytem"</strong> lub „sławny z przezorności".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Nosił je <strong>Przemysł II</strong> (1257–1296) — pierwszy od wieków król Polski po okresie rozbicia dzielnicowego, koronowany w 1295 r. Imię typowo polskie, używane od wczesnego średniowiecza.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Przemek, Przemo, Przemeczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Imię typowo polskie, bez bezpośrednich odpowiedników w innych językach. Sporadycznie używana forma Przemysl w języku czeskim.</p></div>',

  "Aleksander": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Aleksander pochodzi z języka <strong>greckiego</strong> — złożone z <em>alexein</em> (bronić, chronić) i <em>aner/andros</em> (mężczyzna), co oznacza <strong>„obrońca ludzi"</strong> lub „ten, kto chroni mężów".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię rozsławił <strong>Aleksander Wielki</strong> (356–323 p.n.e.) — macedoński król i zdobywca, jeden z największych wodzów w historii. W Polsce nosił je m.in. <strong>Aleksander Jagiellończyk</strong> — król Polski (1501–1506).</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Olek, Aleksio, Aleks, Olo</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Alexander (ang., niem.), Alexandre (franc.), Alejandro (hiszp.), Alessandro (wł.), Александр (ros.)</p></div>',

  "Izabela": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Izabela pochodzi ze średniowiecznej prowansalskiej formy imienia <strong>Elżbieta</strong>, wywodzącej się z hebrajskiego <em>eliszewa</em> — <strong>„Bóg jest moją przysięgą"</strong>. Może też nawiązywać do biblijnej Jezebel.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Pierwszą Polką o tym imieniu była <strong>Izabela Jagiellonka</strong> (1519–1559). Do Polski dotarło przez wpływy francuskie. Zdrobnienie Iza funkcjonuje jako samodzielne imię. Dziś nosi je ponad 159 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Iza, Bella, Izabelka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Isabel (hiszp., port.), Isabelle (franc.), Isabella (wł., ang.), Elisabeth (niem.)</p></div>',

  "Helena": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Helena pochodzi z języka <strong>greckiego</strong> — od słowa <em>helene</em> (ἑλένη), co może oznaczać <strong>„blask"</strong>, „pochodnia" lub nawiązywać do słowa „Hellas" (Grecja). Wywodzi się od imienia bogini księżyca Selene.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W mitologii greckiej <strong>Helena Trojańska</strong> — słynna z urody córka Zeusa, uprowadzenie której wywołało wojnę trojańską. W tradycji chrześcijańskiej patronką jest <strong>święta Helena</strong> — matka cesarza Konstantyna Wielkiego.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Hela, Helcia, Helenka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Helen (ang.), Hélène (franc.), Helene (niem.), Elena (hiszp., wł.), Елена (ros.)</p></div>',

  "Weronika": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Weronika pochodzi z języka <strong>greckiego</strong> — złożone z <em>phero</em> (nieść) i <em>nike</em> (zwycięstwo), co oznacza <strong>„niosąca zwycięstwo"</strong>. Popularna etymologia ludowa łączy je z łacińskim <em>vera icon</em> — „prawdziwy obraz".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronką jest <strong>święta Weronika</strong> — kobieta, która według legendy otarła twarz Jezusa chustą podczas drogi na Krzyż. Na chuście miał pozostać cudowny wizerunek Chrystusa.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Wera, Werka, Weronka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Veronica (ang., wł.), Véronique (franc.), Veronika (niem., czes.), Вероника (ros.)</p></div>',

  "Aneta": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Aneta pochodzi z języka <strong>hebrajskiego</strong> — jest francuskim zdrobnieniem od Anna (<em>Anette</em>), wywodzącego się od <em>hannāh</em> oznaczającego <strong>„łaska"</strong>. Do Polski dotarło przez wpływ francuski w XIX wieku.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Znana nosicielka to <strong>Aneta Kręglicka</strong> — Miss World 1989, pierwsza Polka z tym tytułem. Dziś nosi imię ok. 151 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Anetka, Anka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Annette (franc., niem.), Anette (szw.), Annetta (ang.), Aneta (czes., słowac.)</p></div>',

  "Henryk": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Henryk pochodzi ze <strong>starogermańskiego</strong> — złożone z <em>heim</em> (dom) i <em>ric</em> (władca, potęga), co oznacza <strong>„władca domu"</strong> lub „pan w swoim domu". Jest polską formą imienia Heinrich.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Spopularyzowane przez dynastię frankijskich i niemieckich władców. W Polsce nosił je m.in. <strong>Henryk Walezy</strong> (król Polski 1573–1574), kompozytor <strong>Henryk Mikołaj Górecki</strong> i pisarz <strong>Henryk Sienkiewicz</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Henio, Heniu, Heneczek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Henry (ang.), Henri (franc.), Heinrich (niem.), Enrique (hiszp.), Enrico (wł.), Генрих (ros.)</p></div>',

  "Adrian": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Adrian pochodzi z języka <strong>łacińskiego</strong> — od nazwy miasta <em>Hadria</em> (dzisiejsze Atri we Włoszech) lub Morza Adriatyckiego, co oznacza dosłownie <strong>„człowiek z Hadrii"</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Imię nosił cesarz rzymski <strong>Hadrian</strong> (76–138) — budowniczy słynnego Muru Hadriana w Brytanii. W tradycji chrześcijańskiej znany jest papież Hadrian I. W Polsce popularne szczególnie od lat 90. XX w.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Adek, Adrianek</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Adrian (ang., niem., hiszp.), Adrien (franc.), Adriano (wł.), Адриан (ros.)</p></div>',

  "Ewelina": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Ewelina wywodzi się z języka <strong>irlandzkiego</strong> — od celtyckiego <em>Éibhleann</em> oznaczającego <strong>„radość"</strong> lub „blask". Alternatywna etymologia wskazuje na starofrancuskie <em>aveline</em> (z łac. <em>avis</em> — ptak).</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>W Polsce imię upowszechniło się w XX wieku. Dziś nosi je ok. 148 tysięcy Polek. Imieniny obchodzone są 26 maja i 24 grudnia.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Ewelinka, Ewelka</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Eveline (franc., ang.), Evelina (wł.), Evelyn (ang.), Эвелина (ros.)</p></div>',

  "Martyna": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Martyna pochodzi z języka <strong>łacińskiego</strong> — jest żeńską formą imienia Marcin (<em>Martinus</em>), wywodzącego się od imienia boga wojny Marsa. Oznacza <strong>„należąca do Marsa"</strong> lub „bojowa".</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronką jest <strong>święta Martyna z Rzymu</strong> (†226) — dziewica i męczennica, czczona 30 stycznia. W Polsce imię zyskało popularność w XX i XXI wieku. Dziś nosi je ok. 143 tysięcy Polek.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Martynka, Martysia</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Martina (ang., niem., wł., hiszp.), Martine (franc.), Мартина (ros.)</p></div>',

  "Mikołaj": '<div class="name-desc-section"><div class="name-desc-label">Znaczenie imienia</div><p>Imię Mikołaj pochodzi z języka <strong>greckiego</strong> — złożone z <em>nike</em> (zwycięstwo) i <em>laos</em> (lud, naród), co oznacza <strong>„zwycięstwo ludu"</strong>. Jest polską formą greckiego Nikolaos.</p></div><div class="name-desc-section"><div class="name-desc-label">Historia</div><p>Patronem jest <strong>święty Mikołaj z Miry</strong> (IV w.) — biskup, patron dzieci, marynarzy i kupców. Jego postać zainspirowała tradycję Świętego Mikołaja przynoszącego prezenty 6 grudnia. Imię nosił też astronom <strong>Mikołaj Kopernik</strong>.</p></div><div class="name-desc-section"><div class="name-desc-label">Zdrobnienia</div><p>Mikołajek, Miko, Nikola</p></div><div class="name-desc-section"><div class="name-desc-label">Odpowiedniki w innych językach</div><p>Nicholas (ang.), Nicolas (franc.), Nikolaus (niem.), Nicolás (hiszp.), Nicola (wł.), Николай (ros.)</p></div>',

};
